site_name: OpenPAV
theme:
  name: readthedocs
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
nav:
  - Overview: index.md
  - Installation: installation.md
  - Quick Start: quick_start.md
  - Model Calibration: model_calibration.md
  - Simulation Integration: simulation_integration.md
  - Model Download: model_download.md